"""Shared A3 sheet frame and drafting primitives for Redline drawings.

The look is a "blackprint": black paper, white lines, red for what matters.
Zone border A-F / 1-8, revision block and title block follow defence-style
drawing frames.
"""

from html import escape

DATE = "2026-10-05"
NOTES = [
    "1. Dimensions in mm. Third-angle projection. General tolerances to be defined (ISO 2768-m proposed).",
    "2. Board outlines: maker or distributor data cited in hardware/netlist.json; others are indicative envelopes.",
    "3. Heights, connectors and positions of openings are indicative and must be measured on the chosen parts.",
    "4. Geometry and sheets generated by cad/generate.py (build123d 0.13.0); checks run with --check.",
]


def txt(x, y, value, size=3, cls="label", anchor="start"):
    return f'<text x="{x:.2f}" y="{y:.2f}" class="{cls}" font-size="{size}" text-anchor="{anchor}">{escape(str(value))}</text>'


def line(x1, y1, x2, y2, cls="thin"):
    return f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}" class="{cls}"/>'


def rect(x, y, w, h, cls="frame"):
    return f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" class="{cls}"/>'


def dim_h(x1, x2, y, ey, label):
    return (line(x1, ey, x1, y - 2, "extension") + line(x2, ey, x2, y - 2, "extension") +
            line(x1, y, x2, y, "dimension") +
            f'<path class="arrow" d="M{x1:.2f},{y:.2f} l3,-1 l0,2 z M{x2:.2f},{y:.2f} l-3,-1 l0,2 z"/>' +
            txt((x1 + x2) / 2, y - 1.7, label, 2.8, "dimension-text", "middle"))


def dim_v(y1, y2, x, ex, label):
    mid = (y1 + y2) / 2
    return (line(ex, y1, x + 2, y1, "extension") + line(ex, y2, x + 2, y2, "extension") +
            line(x, y1, x, y2, "dimension") +
            f'<path class="arrow" d="M{x:.2f},{y1:.2f} l-1,3 l2,0 z M{x:.2f},{y2:.2f} l-1,-3 l2,0 z"/>' +
            f'<text x="{x - 2:.2f}" y="{mid:.2f}" transform="rotate(-90 {x - 2:.2f} {mid:.2f})" class="dimension-text" font-size="2.8" text-anchor="middle">{escape(str(label))}</text>')


def balloon(x, y, tx, ty, number):
    """Find-number balloon at (tx, ty) with a leader ending on a dot at (x, y)."""
    return (line(x, y, tx, ty, "leader") + f'<circle cx="{x:.2f}" cy="{y:.2f}" r=".7" class="dot"/>' +
            f'<circle cx="{tx:.2f}" cy="{ty:.2f}" r="3.6" class="balloon"/>' +
            txt(tx, ty + 1.15, number, 3.2, "label-bold", "middle"))


def table(x, y, widths, rows, row_h=5.2, header_size=2.3, size=2.15):
    out = [rect(x, y, sum(widths), row_h * len(rows), "frame")]
    for r, row in enumerate(rows):
        yy = y + r * row_h
        if r:
            out.append(line(x, yy, x + sum(widths), yy, "grid-line"))
        else:
            out.append(rect(x, yy, sum(widths), row_h, "head"))
        xx = x
        for c, (w, cell) in enumerate(zip(widths, row)):
            if c:
                out.append(line(xx, y, xx, y + row_h * len(rows), "grid-line"))
            out.append(txt(xx + 1.4, yy + row_h * 0.68, cell, header_size if r == 0 else size,
                           "label-bold" if r == 0 else "label"))
            xx += w
    return "".join(out)


STYLE = '''<style>
  .object{fill:none;stroke:#f5f5f5;stroke-width:.34;stroke-linecap:round;stroke-linejoin:round}
  .hidden{fill:none;stroke:#9a9aa2;stroke-width:.16;stroke-dasharray:1.5 1.2}
  .thin,.extension{fill:none;stroke:#c9c9cf;stroke-width:.16}
  .leader{stroke:#f5f5f5;stroke-width:.2}
  .dot{fill:#f5f5f5}
  .balloon{fill:#0b0b0c;stroke:#f5f5f5;stroke-width:.3}
  .dimension{stroke:#f5f5f5;stroke-width:.16} .dimension-text{font-family:Arial,sans-serif;fill:#f5f5f5}
  .arrow{fill:#f5f5f5} .label{font-family:Arial,sans-serif;fill:#fff}
  .label-bold{font-family:Arial,sans-serif;fill:#fff;font-weight:700}
  .sub{font-family:Arial,sans-serif;fill:#bdbdc4}
  .accent{font-family:Arial,sans-serif;fill:#ff2a2a;font-weight:700}
  .center{stroke:#9a9aa2;stroke-width:.15;stroke-dasharray:5 1 1 1}
  .cut{stroke:#fff;stroke-width:.42;stroke-dasharray:8 1 2 1}
  .frame{fill:none;stroke:#f5f5f5;stroke-width:.3}
  .border{fill:none;stroke:#f5f5f5;stroke-width:.5}
  .grid-line{stroke:#9a9aa2;stroke-width:.15}
  .head{fill:#17171b;stroke:#f5f5f5;stroke-width:.3}
  .wire{fill:none;stroke:#ff2a2a;stroke-width:.45;stroke-linecap:round;stroke-linejoin:round}
  .wire-rf{fill:none;stroke:#ff2a2a;stroke-width:.45;stroke-dasharray:2 .8}
  .pin{fill:#f5f5f5}
</style>'''

DEFS = '''<defs>
  <pattern id="grid-small" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M5 0H0V5" fill="none" stroke="#ffffff" stroke-width=".08" opacity=".10"/></pattern>
  <pattern id="grid-large" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#ffffff" stroke-width=".14" opacity=".16"/></pattern>
  <pattern id="hatch" width="2.6" height="2.6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><path d="M0 0 V2.6" stroke="#d6d6dc" stroke-width=".18"/></pattern>
  <pattern id="hatch2" width="1.6" height="1.6" patternUnits="userSpaceOnUse" patternTransform="rotate(-45)"><path d="M0 0 V1.6" stroke="#ff2a2a" stroke-width=".18"/></pattern>
</defs>
<rect width="420" height="297" fill="#0b0b0c"/>
<rect width="420" height="297" fill="url(#grid-small)"/>
<rect width="420" height="297" fill="url(#grid-large)"/>'''


def sheet_start(number, title, docno, scale_note="1:1 unless noted", total=5, date=DATE,
                subtitle="Redline tracker and black box, board RL-MB-01 (nRF9151)",
                revision="Hardware concept RL-MB-01", notes=NOTES, material="to be defined"):
    """A3 frame: zone border A-F / 1-8, revision block and title block."""
    s = ['<svg xmlns="http://www.w3.org/2000/svg" width="420mm" height="297mm" viewBox="0 0 420 297">', STYLE, DEFS]
    s.append(rect(5, 5, 410, 287, "border"))
    s.append(rect(10, 10, 400, 277, "border"))
    cols, rows = 8, 6
    for i in range(cols):
        x0 = 10 + 400 * i / cols
        if i:
            s.append(line(x0, 5, x0, 10, "frame") + line(x0, 287, x0, 292, "frame"))
        for yy in (8.9, 290.9):
            s.append(txt(x0 + 25, yy, i + 1, 2.6, "label", "middle"))
    for j in range(rows):
        y0 = 10 + 277 * j / rows
        if j:
            s.append(line(5, y0, 10, y0, "frame") + line(410, y0, 415, y0, "frame"))
        for xx in (7.5, 412.5):
            s.append(txt(xx, y0 + 277 / rows / 2 + 1, "ABCDEF"[j], 2.6, "label", "middle"))
    s.append(rect(10, 10, 400, 8, "head"))
    s.append('<path d="M10 18 H410" stroke="#ff2a2a" stroke-width=".7"/>')
    s.append(txt(14, 15.6, "REDLINE / RL-MB-01", 3.6, "label-bold"))
    s.append(txt(80, 15.6, "CONCEPT STUDY - PROVISIONAL DIMENSIONS - DO NOT BUILD WITHOUT REVIEW", 2.5, "accent"))
    s.append(table(318, 21, [10, 52, 22], [["REV", "DESCRIPTION", "DATE"], ["0", revision, date]], 4.6, 2.2, 2.1))
    tb = 250
    s.append(f'<path d="M10 {tb} H410 M232 {tb} V287 M232 {tb + 13} H410 M232 {tb + 25} H410 '
             f'M292 {tb + 13} V287 M342 {tb + 13} V287 M372 {tb + 13} V287" class="border"/>')
    s.append(txt(14, tb + 6, "GENERAL NOTES", 2.8, "label-bold"))
    for i, n in enumerate(notes):
        s.append(txt(14, tb + 12 + i * 5.6, n, 2.35, "sub"))
    s.append(txt(236, tb + 6.5, title, 4, "label-bold"))
    s.append(txt(236, tb + 11, subtitle, 2.4, "sub"))
    for x, k, v in [(236, "DRAWING NO.", docno), (296, "SCALE", scale_note), (346, "REV", "0"), (376, "SHEET", f"{number} / {total}")]:
        s.append(txt(x, tb + 17, k, 2, "sub"))
        s.append(txt(x, tb + 22.4, v, 2.8, "label-bold"))
    s.append(txt(236, tb + 29.5, "DRAWN BY: M. ABAAQIL", 2.2, "sub"))
    s.append(txt(296, tb + 29.5, f"DATE: {date}", 2.2, "sub"))
    s.append(txt(346, tb + 29.5, f"MATERIAL: {material}", 2.2, "sub"))
    return s
